spring:
  application:
    name: Auth-Service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
server:
  port: 9090

logging:
  file:
    path: logs

url:
  service:
    web: http://localhost:3000
    
jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437

resilience4j:
  ratelimiter:
    instances:
      authLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
